# GO Term Analysis

In [9]:
import pandas as pd 
import pickle
import seaborn as sns

# Load Data

## TPM Data for each Loci

In [68]:
avg_log_ratio_tpm_file = "../data/avg_log_ratio_scaled.csv"

df_avg_log_ratio_tpm = pd.read_csv(avg_log_ratio_tpm_file).fillna('')

In [69]:
df_avg_log_ratio_tpm

,locus_tag,LanzaTech,MeOH,NO3_lowO2_slow_growth,NoCu,NoLanthanum,WT_control,WithLanthanum,aa3_KO,crotonic_acid,...,highO2_slow_growth,lowCH4,lowCu,lowO2_fast_growth,lowO2_low_iron_fast_growth,lowO2_slow_growth,medCu,slow_growth,uMax,unknown
0,EQU24_RS00005,-0.515808,-0.012058,-0.480048,-0.163349,-0.648447,-0.037469,-0.491013,-0.410117,-0.485123,...,0.060397,-0.186470,-0.136377,-0.203679,-0.487435,-0.243069,0.044174,-0.122244,0.185208,-0.620522
1,EQU24_RS00010,0.480568,-0.659004,-0.218643,0.075821,-0.485571,-0.114821,-0.462526,0.094641,-0.209870,...,0.504025,-0.305931,0.204399,-0.103679,-0.283817,0.062219,0.461263,0.103303,0.191813,-0.798028
2,EQU24_RS00015,-1.072637,0.327816,-0.461533,-0.212764,-0.583017,-0.648530,-0.633792,-0.917224,-0.048206,...,0.138747,-0.385615,-0.106453,0.142845,-0.057250,-0.235794,0.034638,-0.609406,0.158782,-0.753895
3,EQU24_RS00020,0.723618,-1.032390,0.072132,-0.253222,-0.352283,0.183488,-0.292974,0.144541,0.167185,...,-0.108216,-0.132304,-0.051795,-0.311922,0.060748,-0.078771,0.169326,0.274118,0.198566,-0.532597
4,EQU24_RS00025,0.424262,-0.479325,0.028098,0.116538,-0.261659,0.082847,-0.454102,-0.051229,0.045575,...,0.450111,0.011533,0.240761,-0.573878,0.722346,0.029248,0.311967,0.268652,0.181731,-0.011128
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4208,EQU24_RS22135,-0.445389,-0.627550,-1.170665,-0.396450,-1.877416,-0.819438,-1.715711,-0.966683,-0.144739,...,-1.123350,0.097626,-0.295041,0.153868,0.071796,-0.825055,0.213758,-1.168263,0.206290,-0.784262
4209,EQU24_RS22140,0.309593,-1.327737,-1.065740,-0.706776,-1.812366,-0.818297,-1.749368,-0.654022,-0.239402,...,-1.305006,-0.407547,-0.418638,0.243782,-0.820586,-0.906017,-0.091223,-0.946392,0.229381,-1.159766
4210,EQU24_RS22145,-1.028264,-0.395724,-1.265702,-0.657315,-2.492508,-0.803695,-2.140667,-0.926349,-0.555916,...,-1.210127,0.079368,-0.380479,0.362696,-0.218650,-0.747930,0.020182,-0.861652,0.229635,-1.151259
4211,EQU24_RS22150,-0.670633,-0.279756,-1.404703,-0.775605,-2.384838,-1.209018,-2.238072,-1.143556,-1.210963,...,-1.730685,0.119592,-0.495403,0.627209,-0.443132,-1.002031,-0.030594,-0.961987,0.233474,-1.159678
4212,EQU24_RS22155,-0.665398,-1.464863,-1.306404,-0.270004,-1.906208,-0.579939,-1.735955,-0.504679,-1.163303,...,-1.670054,-1.197919,-0.145297,0.580148,-1.489146,-0.824026,0.390702,-0.554407,0.233606,-1.240447

## Labels for ideal clusters

By Dr. Lidstrom's sanity check of the cluster composition, the two ideal clusterings that will be used are kMeans with k = 19, and BIRCH with threshold = 0.48, branching factor = 50.0, and k = 31

In [74]:
kmeans_19_file = "../data/cluster_labels/kmeans, param1 = 19, param2 = nan, param3 = nan"

df_kmeans_labels = pd.read_csv(kmeans_19_file).fillna('')
df_kmeans_labels

,cluster_num,type_of_loci,genes,gene_counts
0,0,inducible_copper_loci,['EQU24_RS02555'],1
1,1,inducible_copper_loci,[],0
2,2,inducible_copper_loci,[],0
3,3,inducible_copper_loci,[],0
4,4,inducible_copper_loci,[],0
...,...,...,...,...
128,14,else,"['EQU24_RS01495', 'EQU24_RS17700', 'EQU24_RS06...",54
129,15,else,"['EQU24_RS10985', 'EQU24_RS10670', 'EQU24_RS11...",317
130,16,else,"['EQU24_RS07140', 'EQU24_RS17515', 'EQU24_RS21...",504
131,17,else,"['EQU24_RS03170', 'EQU24_RS19980', 'EQU24_RS07...",499
132,18,else,"['EQU24_RS08850', 'EQU24_RS11115', 'EQU24_RS19...",24

In [76]:
birch_31_file = "../data/cluster_labels/birch, param1 = 0.48, param2 = 50.0, param3 = 31.0"

df_birch_labels = pd.read_csv(birch_31_file).fillna('')
df_birch_labels

,cluster_num,type_of_loci,genes,gene_counts
0,0,inducible_copper_loci,[],0
1,1,inducible_copper_loci,[],0
2,2,inducible_copper_loci,[],0
3,3,inducible_copper_loci,[],0
4,4,inducible_copper_loci,[],0
...,...,...,...,...
212,26,else,"['EQU24_RS14335', 'EQU24_RS21735', 'EQU24_RS13...",18
213,27,else,"['EQU24_RS12980', 'EQU24_RS02260', 'EQU24_RS00...",150
214,28,else,"['EQU24_RS08675', 'EQU24_RS21490', 'EQU24_RS13...",84
215,29,else,"['EQU24_RS16845', 'EQU24_RS01590', 'EQU24_RS04...",51
216,30,else,"['EQU24_RS18860', 'EQU24_RS12815', 'EQU24_RS05...",8

## GO Terms For Loci

In [77]:
blast_2_go_file = "../data/go_terms/blast_2_go"

df_go_terms = pd.read_csv("../data/go_terms/blast_2_go").fillna('')
df_go_terms

               loci                                           go_terms
0     EQU24_RS00005  ['GO:0003688', 'GO:0005524', 'GO:0005737', 'GO...
1     EQU24_RS00010  ['GO:0003677', 'GO:0003887', 'GO:0005737', 'GO...
2     EQU24_RS00015  ['GO:0003697', 'GO:0005524', 'GO:0005737', 'GO...
3     EQU24_RS00020  ['GO:0003677', 'GO:0003918', 'GO:0005524', 'GO...
4     EQU24_RS00040                       ['GO:0015562', 'GO:0055085']
...             ...                                                ...
3406  EQU24_RS22135  ['GO:0003924', 'GO:0005515', 'GO:0005525', 'GO...
3407  EQU24_RS22140  ['GO:0005886', 'GO:0015031', 'GO:0016021', 'GO...
3408  EQU24_RS22145                                     ['GO:0005886']
3409  EQU24_RS22150  ['GO:0000049', 'GO:0001682', 'GO:0004526', 'GO...
3410  EQU24_RS22155         ['GO:0003735', 'GO:0005840', 'GO:0006412']

[3411 rows x 2 columns]

# Parallel Coordinate Plot

## Key Functions: 

- Author: Erin
- Modified for Use: Vrishab

In [78]:
def altair_pcoords(df,title,xorder='exp_condition_order'):
    # If more than 30 entries, make 2 columns
    col_num = 1 if len(df['locus_tag'].unique()) <=50 else 2
    
    highlight = alt.selection(type='single', on='mouseover',
                              fields=['desc_string'], nearest=True)
    
    selection = alt.selection_multi(fields=['desc_string'], bind='legend')


    base = alt.Chart(df.sort_values(xorder),
                     title=title
        ).encode(
        x=alt.X(f'{xorder}:N',
                sort=alt.EncodingSortField(field=f"{xorder}:N", op="count")
               ),
        y='mean:Q',
        color=alt.Color('desc_string:N',
                        legend=alt.Legend(title='Gene', 
                                          orient = 'right',
                                          labelLimit=0,
                                          columns=col_num,
                                          symbolLimit=200
                                         )),
        size=alt.value(100)        
    )
    

    lines = base.mark_line().encode(
        size=alt.condition((selection|highlight), alt.value(3), alt.value(1)),
        opacity=alt.condition((selection|highlight), alt.value(1), alt.value(0.5))
    ).add_selection(
        selection,
    ).properties(
         width=600,
         height=400
    ).interactive()
    
    
    points = base.mark_circle().encode(
        tooltip=['locus_tag','product','type','gene_symbol'],
        opacity=alt.condition((selection|highlight), alt.value(1), alt.value(0.2)),
        size=alt.condition((selection|highlight), alt.value(100), alt.value(3))
    ).add_selection(highlight)

    #return points + lines
    return lines + points

def check_cluster_expression(df, cols,cluster_id,title):
    df['desc_string'] = df.apply(lambda row: f"{row['locus_tag']}|{row['gene_symbol']}|{row['product']}",axis=1)
    id_vars = ['locus_tag','gene_symbol','product','type','sys','pc1','pc2','pc3','tsne1','tsne2','cluster_id','desc_string']
    dfm = df.melt(id_vars=id_vars, value_vars=cols,var_name='exp_condition',value_name="mean")
    # altair sort helper
    list_ordering = ['uMax','lowCH4','NoCu','lowCu','medCu','highCu','NO3_lowO2_slow_growth','highO2_slow_growth','lowO2_fast_growth','MeOH','NoLanthanum','WithLanthanum'] 
    dfm["exp_condition_order"] = pd.Categorical(dfm["exp_condition"], categories=list_ordering)
    #return dfm
    return altair_pcoords(dfm[dfm['cluster_id']==cluster_id],title)

# Practice

In [67]:
condition_to_ferm_run_file = "../data/new_sample2condition.txt"

    
# load mapping from sample to condition
with open(condition_to_loci_file,'r') as f:
    loci_to_ferm_run = str(f.readline()[1:(len(f.readline())-1)]).split(',')

    loci_tracker = dict(loci.replace('"', "").strip().split(':') for loci in loci_to_condition)
    
condition_to_ferm_run = {}
    
for exp_run in loci_tracker.keys(): 
    
    cur_condition = loci_tracker[exp_run].strip()
    
    if cur_condition not in condition_to_ferm_run.keys():
        condition_to_ferm_run[cur_condition] = [exp_run]
        print(cur_condition)
        print(condition_to_ferm_run)
        print(condition_to_ferm_run[cur_condition])

        print("BB")
        
    else: 
        condition_to_ferm_run[cur_condition] = condition_to_ferm_run[cur_condition].append(exp_run)


        print(cur_condition)
        print(condition_to_ferm_run[cur_condition])
        print(condition_to_ferm_run)
        print("AA")
    
# df_loci_tracker = pd.DataFrame(loci_tracker.keys(), loci_tracker.values()).reset_index()
# df_loci_tracker.columns = ["condition", "exp_run"]
condition_to_ferm_run

lowO2_slow_growth
{'lowO2_slow_growth': ['5GB1_ferm_Ack_QC_tpm']}
['5GB1_ferm_Ack_QC_tpm']
BB
lowO2_slow_growth
None
{'lowO2_slow_growth': None}
AA
uMax
{'lowO2_slow_growth': None, 'uMax': ['5GB1_FM03_TR1_QC_tpm']}
['5GB1_FM03_TR1_QC_tpm']
BB
uMax
None
{'lowO2_slow_growth': None, 'uMax': None}
AA
lowO2_low_iron_fast_growth
{'lowO2_slow_growth': None, 'uMax': None, 'lowO2_low_iron_fast_growth': ['5GB1_FM11_TR1_QC_tpm']}
['5GB1_FM11_TR1_QC_tpm']
BB
lowO2_low_iron_fast_growth
None
{'lowO2_slow_growth': None, 'uMax': None, 'lowO2_low_iron_fast_growth': None}
AA
lowCH4
{'lowO2_slow_growth': None, 'uMax': None, 'lowO2_low_iron_fast_growth': None, 'lowCH4': ['5GB1_FM12_TR1_tpm']}
['5GB1_FM12_TR1_tpm']
BB
lowCH4
None
{'lowO2_slow_growth': None, 'uMax': None, 'lowO2_low_iron_fast_growth': None, 'lowCH4': None}
AA

AttributeError: 'NoneType' object has no attribute 'append'